### PR TITLE
Reduce Docker Image size by ~ 500MB 

### PR DESCRIPTION
**Pull request by tonymet**
Prune the Docker image by using puppeteer-core and other cleanup .  Reduces cloud costs & improved loading times
* puppeteer-core removes chromium from node-modules
* remove fonts
* update strava.js to use puppeteer-core and reference path.

## BEFORE
```
strava-kudos            latest              5f6d886986c2        About an hour ago   1.02GB
```

##  AFTER
```
strava-kudos            lite-2              bfa73eaad73f        20 minutes ago      578MB
```

## TESTING
```
# run with volume
docker run -v`pwd`:/stravaKudos  --env STRAVA_USER=$STRAVA_USER --env STRAVA_PWD=$STRAVA_PWD strava-kudos:lite-3  node stravaKudos/strava.js
# run without volume
docker run  --env STRAVA_USER=$STRAVA_USER --env STRAVA_PWD=$STRAVA_PWD strava-kudos:lite-3
```

### CODE REVIEW

**Review by plod — APPROVED** [review]
This is fantastic, thanks a lot!

The Dockerfile had not had a lot of love in a while, while I dealt with another bug which was unrelated, was on my radar to come back and sort it out. Now I just need to fix it for multiarch

**Comment by tonymet** [comment]
thanks for the app it's been great. i've been running it on a AWS lightsail server and kudos is working great.  I have a couple other PRs – let me know if you would be interested…

Other PRs
* reduce network load & speed up kudos by rejecting unnecessary HTTP requests (images, stylesheets, analytics)
* reducing log noise

**Comment by tonymet** [comment]
@plod can you tell me which arch's you are targeting? e.g. linux + mac + windows?

**Comment by plod** [comment]
> * reduce network load & speed up kudos by rejecting unnecessary HTTP requests (images, stylesheets, analytics)

definitely see a lot of traffic to cloudfront for pictures that is definitely superflous on my home internet connection
> * reducing log noise

Yeah this is turned up quite noisy but originally before a friend helped with the javascript I didn't have much logging to help me debug.

> @plod can you tell me which arch's you are targeting? e.g. linux + mac + windows?

I'm only really talking linux but at home I run it on a raspberry pi  and the chrome docker step doesn't work `[arch=amd64]` 

I built it on my mac with `docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t plod/stravakudos:latest --push .`

**Pull request merged**
