### PR TITLE
[discuss] Reduce Network Traffic

### PR DESCRIPTION
**Pull request by tonymet**
Quite a few changes here – how would you like me to prepare them to merge? 
* reduce network traffic only to essential (no images, no css, no tracking)
* linting 
* no need for tty
* reduce log noise

it's a large code change, so I wanted to ask your guidance on how to prepare for merge.

### CODE REVIEW

**Comment by tonymet** [comment]
@plod Would like your guidance. Can you pull and test this on your environment, and share feedback?  I wanted to contribute the work, but it's a large diff

**Comment by plod** [comment]
Yes no problem will have a review asap

**Comment by plod** [comment]
not ran it yet, but looks good, I had started to have some failure statuses 429 too many requests, @tonymet have you had any of that?

**Comment by tonymet** [comment]
can you see if you are running it concurrently (e.g. on another instance or multiple processes)? I haven't had any issues with that. It's possible that I have fewer kudos per run.

**Comment by plod** [comment]
you have the same problems as me @tonymet

**Pull request closed without merging**
